### ISSUE TITLE
咨询生成ehr_phenotyping_48h  cxr_phenotyping_48h 等pkl文件的代码

### ISSUE THREAD

**Issue by chunyuxiaodao** [dorothy-yao/drfuse#2]
十分感谢你们杰出的工作！目前我已经按照处理得到metas_with_labels_phenotyping_first_48h.pkl，但是我发现并没有提供ehr_phenotyping_48h_train........  cxr_phenotyping_48h_test等文件的处理代码，请问作者是否能提供这部分代码或者指导？十分感谢！！

**Comment by ZhengxuanSun** [comment]
你好，同问。请问你的问题解决了嘛， 是如何解决的？谢谢。

**Comment by MYW322** [comment]
你好，同问。请问你的问题解决了嘛， 是如何解决的？谢谢。我也想要这几个pkl，拜托你了，我的邮箱是fxbeauty@163.com
