### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by Shivi1112** [dorothy-yao/drfuse#3]
/drfuse$ python main.py
Seed set to 0
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    normalizer.load_params(normalizer_state)
  File "/DATA/drfuse/utils/ehr_normalizer.py", line 43, in load_params
    with open(load_file_path, "rb") as load_file:
FileNotFoundError: [Errno 2] No such file or directory: 'normalizers/ph_ts1.0.input_str_previous.start_time_zero.normalizer'

Also how to get these files ???
'ehr_phenotyping_48h_train.pkl','ehr_phenotyping_48h_val.pkl','ehr_phenotyping_48h_test.pkl','cxr_phenotyping_48h_train.pkl','cxr_phenotyping_48h_val.pkl','cxr_phenotyping_48h_test.pkl',

**Comment by dorothy-yao** [comment]
For the normalizer, we used the one in [Medfuse](https://github.com/nyuad-cai/MedFuse/blob/main/normalizers/ph_ts1.0.input_str%3Aprevious.start_time%3Azero.normalizer) . It has been updated to the code.

For pkl files, they are generated automatically. Please extract data from MIMIC-IV and MIMIC-CXR.

**Comment by Shivi1112** [comment]
Thank you for your reply.

After running your code, I am getting AUPRC = 0.269 for partial and 0.361 for paired, which is significantly lower than the results reported in the paper. Could you please provide the hyperparameters used to reproduce the reported results?

**Comment by dorothy-yao** [comment]
Thank you for your interest in our work. The hyperparameters are described in Section 4.1 - Experiment implementation in the published article. Please kindly refer to the content for the implementation details. Thank you.

**Comment by Shivi1112** [comment]
I have been working with the hyperparameters you provided and applied them to my training process. However, after several runs, I am consistently getting an AUPRC of 0.269 for the partial dataset and 0.361 for the paired dataset. These results are noticeably lower than the reported values in the paper.
Given this, I’m wondering if there might be something I am overlooking or if there are additional details about the setup that I should be aware of. I would greatly appreciate any insights or suggestions you could offer to help me achieve the expected performance.
