### ISSUE TITLE
adaptive_adc_lambda

### ISSUE THREAD

**Issue by JeongSeong** [dorothy-yao/drfuse#5]
what is adaptive_adc_lambda?

it seems you don't use it in the model, so I just removed dependent variables in the model and trainer. 

I think you would better update the code

**Comment by dorothy-yao** [comment]
Thank you for your suggestion. We have reviewed the code again. adaptive_adc_lambda was a parameter used in a previous variant of DrFuse. It is not used in the final version. We have updated the codes and removed them. Thanks again!
