### ISSUE TITLE
请问disease-aware attention fusion module如何应对模态缺失的？

### ISSUE THREAD

**Issue by duoxiangqinzuo** [dorothy-yao/drfuse#6]
您好，我阅读了您的论文，但是没有看懂disease-aware attention fusion module的过程，尤其是不理解它是怎么应对模态缺失的，即h_distinct^CXR不存在的情形。您是否能够给予解答？

**Comment by dorothy-yao** [comment]
您好。CXR模态缺失时，h_distinct^CXR不存在，用h_shared替代。也就是说，CXR模态缺失时，disease-aware attention fusion module的输入只有h_shared和h_distinct^CXR，这时缺失的CXR用全0的img填补，通过encoder输出的h_distinct^CXR后续参与attention计算时会被mask处理掉（见文章eq(7)下方对应mask的描述）。希望这个解答对您有帮助，谢谢您的提问。
